// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.wikia.knowledge.domain;

import java.util.List;
import net.wikia.knowledge.domain.EntityCollectionDataOnDemand;
import net.wikia.knowledge.domain.EntityCollectionIntegrationTest;
import net.wikia.knowledge.repository.EntityCollectionRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EntityCollectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EntityCollectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EntityCollectionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EntityCollectionIntegrationTest: @Transactional;
    
    @Autowired
    EntityCollectionDataOnDemand EntityCollectionIntegrationTest.dod;
    
    @Autowired
    EntityCollectionRepository EntityCollectionIntegrationTest.entityCollectionRepository;
    
    @Test
    public void EntityCollectionIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", dod.getRandomEntityCollection());
        long count = entityCollectionRepository.count();
        Assert.assertTrue("Counter for 'EntityCollection' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testFind() {
        EntityCollection obj = dod.getRandomEntityCollection();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to provide an identifier", id);
        obj = entityCollectionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'EntityCollection' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EntityCollection' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", dod.getRandomEntityCollection());
        long count = entityCollectionRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'EntityCollection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EntityCollection> result = entityCollectionRepository.findAll();
        Assert.assertNotNull("Find all method for 'EntityCollection' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EntityCollection' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", dod.getRandomEntityCollection());
        long count = entityCollectionRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EntityCollection> result = entityCollectionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'EntityCollection' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EntityCollection' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testFlush() {
        EntityCollection obj = dod.getRandomEntityCollection();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to provide an identifier", id);
        obj = entityCollectionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'EntityCollection' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEntityCollection(obj);
        Integer currentVersion = obj.getVersion();
        entityCollectionRepository.flush();
        Assert.assertTrue("Version for 'EntityCollection' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testSaveUpdate() {
        EntityCollection obj = dod.getRandomEntityCollection();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to provide an identifier", id);
        obj = entityCollectionRepository.findOne(id);
        boolean modified =  dod.modifyEntityCollection(obj);
        Integer currentVersion = obj.getVersion();
        EntityCollection merged = entityCollectionRepository.save(obj);
        entityCollectionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EntityCollection' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", dod.getRandomEntityCollection());
        EntityCollection obj = dod.getNewTransientEntityCollection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EntityCollection' identifier to be null", obj.getId());
        entityCollectionRepository.save(obj);
        entityCollectionRepository.flush();
        Assert.assertNotNull("Expected 'EntityCollection' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EntityCollectionIntegrationTest.testDelete() {
        EntityCollection obj = dod.getRandomEntityCollection();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EntityCollection' failed to provide an identifier", id);
        obj = entityCollectionRepository.findOne(id);
        entityCollectionRepository.delete(obj);
        entityCollectionRepository.flush();
        Assert.assertNull("Failed to remove 'EntityCollection' with identifier '" + id + "'", entityCollectionRepository.findOne(id));
    }
    
}
