// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.wikia.knowledge.domain;

import net.wikia.knowledge.domain.EntityIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EntityIntegrationTest_Roo_Configurable {
    
    declare @type: EntityIntegrationTest: @Configurable;
    
}
